#!/user/bib/env bash
# manage processes
if [["s#" == "1" ]]; then
	if [[ "$1" == "start" ]]; then
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process start"
    elif [[ "$1" == "stop" ]]; then
	if test -f "/var/run/my_process.pid"; then
	kill "$(cat /var/run/my_process.pid)"
	fi
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
    elif [[ "$!" == "restart" ]]; then

# stopping the program
if test -f "/var/run/my_process.pid"; then
kill "$(cat /var/run/my_process.pid)"
fi
#starting program
./manage_my_process &
echo "$!" >  /var/run/my_process.pid"
echo "manage_my_process restarted"
else
echo "usage:manage_my_process {start|stop|restart}"
fi
else
echo "usage: manage_my_process {start|stop|resstart}"
fi

